# Generated by Django 5.1.1 on 2024-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
    ]
