# Generated by Django 5.1.1 on 2024-09-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
