# Generated by Django 5.1.1 on 2024-09-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesite', '0002_remove_profile_last_edited_by_alter_userrole_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='DraftProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
