# Generated by Django 5.1.1 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesite', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouncer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileSection',
        ),
    ]
