# Generated by Django 5.1.1 on 2024-09-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesite', '0005_bouncer_delete_profilesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouncer',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
