# Generated by Django 5.1.1 on 2024-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesite', '0006_bouncer_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouncer',
            name='purpose',
            field=models.CharField(choices=[('pr', 'profilesite'), ('bl', 'blogs')], default='pr', max_length=2),
        ),
    ]
